export const ROUTES = {
  AUTH_LOGIN: '/api/auth/login',
  AUTH_SIGNUP: '/api/auth/signup',
  AUTH_ME: '/api/auth/me',
  AUTH_FORGOT_PASSWORD: '/api/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_CHANGE_PASSWORD: '/api/auth/change-password',
  STUDENT_NOTIFICATIONS: '/api/student/notifications',
  STUDENT_NOTIFICATIONS_READ_ALL: '/api/student/notifications/read-all',
  STUDENT_NOTIFICATION_READ: '/api/student/notifications',
  STUDENT_DASHBOARD_STATS: '/api/student/dashboard-stats',
  STUDENT_COURSES: '/api/student/courses',
  STUDENT_COURSE_LESSONS: (courseId: string) => `/api/student/courses/${courseId}/lessons`,
  STUDENT_LESSON_TOGGLE: (lessonId: string) => `/api/student/lessons/${lessonId}/toggle`,
  STUDENT_PRACTICE_SUBMISSIONS: '/api/student/practice/submissions',
  STUDENT_PRACTICE_SUBMIT: '/api/student/practice/submit',
  STUDENT_MOCK_TESTS: '/api/student/mock-tests',
  STUDENT_MOCK_ATTEMPTS: '/api/student/mock-tests/attempts',
  STUDENT_MOCK_ACTIVE: '/api/student/mock-tests/active',
  STUDENT_MOCK_SAVE_PROGRESS: '/api/student/mock-tests/save-progress',
  STUDENT_MOCK_COMPLETE: '/api/student/mock-tests/complete',
  STUDENT_MOCK_GENERATE: '/api/student/mock-tests/generate',
  STUDENT_MOCK_SUBMIT: '/api/student/mock-tests/submit',
  STUDENT_DIAGNOSTIC_STATE: '/api/student/diagnostic-state',
  STUDENT_DIAGNOSTIC_SUBMIT: '/api/student/diagnostic/submit',
  STUDENT_FLASHCARDS: '/api/student/flashcards',
  STUDENT_FLASHCARD_TOGGLE: (cardId: string) => `/api/student/flashcards/${cardId}/toggle`,
  STUDENT_COUPON_VALIDATE: '/api/student/coupon/validate',
  STUDENT_SUBSCRIBE: '/api/student/subscribe',
  STUDENT_UNSUBSCRIBE: '/api/student/unsubscribe',
  STUDENT_CUSTOM_QUESTIONS: '/api/student/custom-questions',
  TEACHER_SUBMISSIONS: '/api/teacher/submissions',
  TEACHER_STUDENTS: '/api/teacher/students',
  TEACHER_CUSTOM_TASKS: '/api/teacher/custom-tasks',
  TEACHER_GRADE: '/api/teacher/grade',
  TEACHER_GRADE_SUBMISSION: (id: string) => `/api/teacher/submissions/${id}/grade`,
  TEACHER_ROSTER: '/api/teacher/roster',
  TEACHER_ANALYTICS: '/api/teacher/analytics',
  ADMIN_USERS: '/api/admin/users',
  ADMIN_USER_ROLE: (id: string) => `/api/admin/users/${id}/role`,
  ADMIN_USER_STATUS: (id: string) => `/api/admin/users/${id}/status`,
  ADMIN_USER_TIER: (id: string) => `/api/admin/users/${id}/tier`,
  ADMIN_COUPONS: '/api/admin/coupons',
  ADMIN_BACKUP: '/api/admin/backup',
  ADMIN_LOGS: '/api/admin/logs',
  ADMIN_JOBS: '/api/admin/jobs',
  ADMIN_AUDIT_LOGS: '/api/admin/audit-logs',
  ADMIN_SYSTEM_METRICS: '/api/admin/system-metrics',
  ADMIN_QUESTION_BANK: '/api/admin/question-bank',
  ADMIN_QUESTION_BANK_ITEM: (id: string) => `/api/admin/question-bank/${id}`,
  ADMIN_QUESTION_BANK_STATUS: (id: string) => `/api/admin/question-bank/${id}/status`,
  STUDENT_QUESTIONS: '/api/student/questions',
  STUDENT_PRACTICE_ATTEMPT_START: '/api/student/practice/attempts/start',
  STUDENT_PRACTICE_ATTEMPT_PLAY_PROMPT: (attemptId: string) => `/api/student/practice/attempts/${attemptId}/play-prompt`,
  STUDENT_PRACTICE_ATTEMPT_AUDIO_UPLOAD: (attemptId: string) => `/api/student/practice/attempts/${attemptId}/audio-upload`,
  STUDENT_PRACTICE_ATTEMPT_SUBMIT: (attemptId: string) => `/api/student/practice/attempts/${attemptId}/submit`,
  STUDENT_PRACTICE_ATTEMPT_GET: (attemptId: string) => `/api/student/practice/attempts/${attemptId}`,
  STUDENT_PRACTICE_ATTEMPT_RESULT: (attemptId: string) => `/api/student/practice/attempts/${attemptId}/result`,
  STUDENT_PRACTICE_QUESTIONS: '/api/student/questions',
  STUDENT_PRACTICE_QUESTIONS_COUNTS: '/api/student/questions/counts',
  UPLOAD: '/api/upload',
  SEED: '/api/seed',
} as const;

export type RouteFunction<T extends (...args: any[]) => string> = T;
