import React, { useState, useEffect } from 'react';
import { useGlobalContext } from './ThemeContext';
import { BookOpen, Users, FileText, BarChart, Edit3, Plus, Clock, Activity } from 'lucide-react';

export const TeacherUI: React.FC = () => {
  const { theme, apiFetch, role } = useGlobalContext();
  const [activeTab, setActiveTab] = useState<'dashboard' | 'students' | 'submissions' | 'mocktests' | 'progress' | 'notes'>('dashboard');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [dash, setDash] = useState<any>(null);
  const [students, setStudents] = useState<any[]>([]);
  const [selectedStudent, setSelectedStudent] = useState<any>(null);
  const [submissions, setSubmissions] = useState<any[]>([]);
  const [mockTests, setMockTests] = useState<any[]>([]);
  const [learningProgress, setLearningProgress] = useState<any>(null);
  const [notes, setNotes] = useState<any[]>([]);
  const [newNote, setNewNote] = useState({ studentId: '', text: '' });
  const [editingNote, setEditingNote] = useState<any>(null);
  const [feedbackText, setFeedbackText] = useState('');
  const [feedbackId, setFeedbackId] = useState('');
  const [studentSearch, setStudentSearch] = useState('');
  const [subStatusFilter, setSubStatusFilter] = useState('');
  const [mtStatusFilter, setMtStatusFilter] = useState('');

  const load = async (url: string) => { try { return await apiFetch(url); } catch { return null; } };

  const loadAll = async () => {
    if (role !== 'teacher' && role !== 'admin') return;
    setLoading(true); setError('');
    try { const [d, st, su, mt, lp, n] = await Promise.all([load('/api/teacher/dashboard'), load('/api/teacher/students'), load('/api/teacher/submissions'), load('/api/teacher/mock-tests'), load('/api/teacher/learning-progress'), load('/api/teacher/notes')]); setDash(d); setStudents(st||[]); setSubmissions(su||[]); setMockTests(mt||[]); setLearningProgress(lp); setNotes(n||[]); }
    catch (e: any) { setError(e.message); } finally { setLoading(false); }
  };
  useEffect(() => { loadAll(); }, [apiFetch, role]);

  const filteredStudents = students.filter(s => !studentSearch || s.name?.toLowerCase().includes(studentSearch.toLowerCase()) || s.email?.toLowerCase().includes(studentSearch.toLowerCase()));
  const filteredSubs = submissions.filter(s => !subStatusFilter || s.status === subStatusFilter);
  const filteredMT = mockTests.filter(m => !mtStatusFilter || m.status === mtStatusFilter);

  if (loading) return <div className="max-w-7xl mx-auto px-4 py-24 text-center text-gray-400">Loading Teacher Portal...</div>;
  if (error) return <div className="max-w-7xl mx-auto px-4 py-24 text-center"><p className="text-red-400 text-sm mb-4">{error}</p><button onClick={loadAll} className="px-4 py-2 bg-emerald-500 text-white rounded-xl text-xs">Retry</button></div>;

  const tabs = [{id:'dashboard',label:'Dashboard',icon:BarChart},{id:'students',label:'Students',icon:Users},{id:'submissions',label:'Submissions',icon:FileText},{id:'mocktests',label:'Mock Tests',icon:Clock},{id:'progress',label:'Progress',icon:Activity},{id:'notes',label:'Notes',icon:Edit3}];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 flex flex-col lg:flex-row gap-8">
      <div className="lg:w-1/5 space-y-4">
        <div className={`p-5 rounded-3xl border ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}>
          <div className="flex items-center gap-2 mb-4 border-b border-gray-850 pb-3"><BookOpen className="w-5 h-5 text-emerald-400"/><h2 className="text-sm font-bold font-mono tracking-widest uppercase text-gray-300">TEACHER</h2></div>
          <div className="space-y-1">{tabs.map(t=><button key={t.id} onClick={()=>setActiveTab(t.id as any)} className={`w-full text-left p-2.5 rounded-xl text-xs font-semibold flex items-center gap-2.5 transition-all cursor-pointer ${activeTab===t.id?'bg-emerald-500 text-white shadow':'text-gray-400 hover:text-white hover:bg-white/5'}`}><t.icon className="w-4 h-4"/>{t.label}</button>)}</div>
        </div>
      </div>
      <div className="flex-1 space-y-6">
        {activeTab==='dashboard'&&dash&&<div className="space-y-6"><h3 className="text-sm font-bold uppercase tracking-widest font-mono text-gray-400">Dashboard</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{l:'Assigned',v:dash.assignedCount},{l:'Submissions',v:dash.totalSubmissions},{l:'Pending',v:dash.pendingScoring},{l:'Scored',v:dash.scoredCount}].map(k=><div key={k.l} className={`p-5 rounded-2xl border text-center ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><p className="text-2xl font-black text-emerald-400">{k.v}</p><p className="text-[10px] font-mono text-gray-500 uppercase mt-1">{k.l}</p></div>)}</div></div>}

        {activeTab==='students'&&<div className="space-y-4"><div className="flex gap-3 items-center"><h3 className="text-sm font-bold uppercase tracking-widest font-mono text-gray-400">Students ({filteredStudents.length})</h3><input value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} placeholder="Search..." className="px-2 py-1.5 rounded text-xs bg-gray-950 border border-gray-850 text-white w-40"/></div>
          {filteredStudents.length===0?<p className="text-gray-500 text-sm py-4">No assigned students.</p>:<div className={`overflow-hidden rounded-2xl border ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><table className="w-full text-left text-xs"><thead><tr className="border-b font-mono text-gray-500 uppercase text-[10px] bg-gray-950/40"><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Target</th><th className="p-3">Avg</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody className="divide-y divide-gray-850">{filteredStudents.map(s=><tr key={s.id} className="hover:bg-white/5"><td className="p-3 font-bold">{s.name}</td><td className="p-3 text-gray-400 text-[10px]">{s.email}</td><td className="p-3">{s.targetScore||'—'}</td><td className="p-3 font-mono text-emerald-400">{s.currentAvg||'—'}</td><td className="p-3"><span className={`text-[9px] font-bold px-2 py-0.5 rounded uppercase ${s.status==='Active'?'bg-emerald-500/10 text-emerald-400':'bg-red-500/10 text-red-400'}`}>{s.status}</span></td><td className="p-3"><button onClick={async()=>{try{setSelectedStudent(await load(`/api/teacher/students/${s.id}`))}catch{}}} className="px-2 py-1 bg-blue-500/10 hover:bg-blue-500 text-blue-400 hover:text-white rounded text-[10px] font-bold">View</button></td></tr>)}</tbody></table></div>}
        </div>}

        {activeTab==='submissions'&&<div className="space-y-3"><div className="flex gap-3 items-center"><h3 className="text-sm font-bold uppercase tracking-widest font-mono text-gray-400">Submissions</h3><select value={subStatusFilter} onChange={e=>setSubStatusFilter(e.target.value)} className="px-2 py-1.5 rounded text-xs bg-gray-950 border border-gray-850 text-white"><option value="">All</option><option value="pending">Pending</option><option value="graded">Scored</option></select></div>
          {filteredSubs.length===0?<p className="text-gray-500 text-sm py-4">No submissions from assigned students.</p>:<div className={`overflow-hidden rounded-2xl border ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><table className="w-full text-left text-xs"><thead><tr className="border-b font-mono text-gray-500 uppercase text-[10px] bg-gray-950/40"><th className="p-3">Student</th><th className="p-3">Task</th><th className="p-3">Status</th><th className="p-3">Score</th><th className="p-3">Feedback</th></tr></thead><tbody className="divide-y divide-gray-850">{filteredSubs.map(s=><tr key={s.id} className="hover:bg-white/5"><td className="p-3">{s.studentName}</td><td className="p-3 font-mono">{s.taskCode}</td><td className={`p-3 ${s.status==='graded'?'text-emerald-400':'text-amber-400'}`}>{s.status}</td><td className="p-3 font-mono">{s.score??'—'}</td><td className="p-3"><div className="flex gap-1"><input value={feedbackId===s.id?feedbackText:''} onChange={e=>{setFeedbackId(s.id);setFeedbackText(e.target.value)}} placeholder="Feedback..." className="px-2 py-1 rounded text-[10px] bg-gray-950 border border-gray-850 text-white w-24"/><button onClick={async()=>{if(!feedbackText)return;await apiFetch(`/api/teacher/submissions/${s.id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({feedback:feedbackText})});setFeedbackText('');setFeedbackId('');loadAll()}} className="px-2 py-1 bg-emerald-500/10 hover:bg-emerald-500 text-emerald-400 hover:text-white rounded text-[10px] font-bold">Save</button></div></td></tr>)}</tbody></table></div>}
        </div>}

        {activeTab==='mocktests'&&<div className="space-y-3"><div className="flex gap-3 items-center"><h3 className="text-sm font-bold uppercase tracking-widest font-mono text-gray-400">Mock Tests</h3><select value={mtStatusFilter} onChange={e=>setMtStatusFilter(e.target.value)} className="px-2 py-1.5 rounded text-xs bg-gray-950 border border-gray-850 text-white"><option value="">All</option><option value="Completed">Completed</option><option value="In Progress">In Progress</option></select></div>
          {filteredMT.length===0?<p className="text-gray-500 text-sm py-4">No mock tests from assigned students.</p>:<div className={`overflow-hidden rounded-2xl border ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><table className="w-full text-left text-xs"><thead><tr className="border-b font-mono text-gray-500 uppercase text-[10px] bg-gray-950/40"><th className="p-3">Student</th><th className="p-3">Title</th><th className="p-3">Type</th><th className="p-3">Score</th><th className="p-3">Date</th></tr></thead><tbody className="divide-y divide-gray-850">{filteredMT.map(m=><tr key={m.id} className="hover:bg-white/5"><td className="p-3">{m.studentName}</td><td className="p-3 truncate max-w-[150px]">{m.title}</td><td className="p-3">{m.type}</td><td className="p-3 font-mono text-emerald-400">{m.overallScore}</td><td className="p-3 text-gray-500 text-[10px]">{m.date}</td></tr>)}</tbody></table></div>}
        </div>}

        {activeTab==='progress'&&learningProgress&&<div className="space-y-6"><h3 className="text-sm font-bold uppercase tracking-widest font-mono text-gray-400">Learning Progress</h3><div className="grid grid-cols-3 gap-4">{[{l:'Assigned',v:learningProgress.assignedStudents},{l:'Lessons Done',v:learningProgress.totalLessonsCompleted},{l:'Cards Mastered',v:learningProgress.totalFlashcardsMastered}].map(k=><div key={k.l} className={`p-5 rounded-2xl border text-center ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><p className="text-2xl font-black text-emerald-400">{k.v}</p><p className="text-[10px] font-mono text-gray-500 uppercase mt-1">{k.l}</p></div>)}</div></div>}

        {activeTab==='notes'&&<div className="space-y-4"><div className="flex justify-between items-center"><h3 className="text-sm font-bold uppercase tracking-widest font-mono text-gray-400">Notes</h3><button onClick={()=>setNewNote({studentId:'',text:''})} className="px-3 py-1.5 bg-emerald-500 text-white rounded-xl text-xs font-bold flex items-center gap-1"><Plus className="w-3 h-3"/>New</button></div>
          {newNote.text!==undefined&&<div className={`p-4 rounded-2xl border space-y-3 ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><select value={newNote.studentId} onChange={e=>setNewNote({...newNote,studentId:e.target.value})} className="w-full px-2 py-1.5 rounded text-xs bg-gray-950 border border-gray-850 text-white"><option value="">Select student...</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><textarea value={newNote.text} onChange={e=>setNewNote({...newNote,text:e.target.value})} placeholder="Note..." rows={3} className="w-full px-3 py-1.5 rounded text-xs bg-gray-950 border border-gray-850 text-white resize-none"/><div className="flex gap-2"><button onClick={async()=>{if(!newNote.studentId||!newNote.text)return;await apiFetch('/api/teacher/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(newNote)});setNewNote({studentId:'',text:''});loadAll()}} className="px-4 py-2 bg-emerald-500 text-white rounded-xl text-xs font-bold">Save</button><button onClick={()=>setNewNote({studentId:'',text:''})} className="px-4 py-2 bg-gray-800 text-gray-300 rounded-xl text-xs">Cancel</button></div></div>}
          {notes.length===0?<p className="text-gray-500 text-sm py-4">No notes yet.</p>:<div className="space-y-2">{notes.map(n=>{return(<div key={n.id} className={`p-4 rounded-2xl border ${theme==='dark'?'bg-[#0f1322] border-gray-850':'bg-white border-gray-200'}`}><div className="flex justify-between items-start mb-2"><span className="text-xs font-bold text-emerald-400">{n.student?.name}</span><span className="text-[10px] text-gray-500">{new Date(n.updatedAt).toLocaleString()}</span></div>{editingNote?.id===n.id?<><textarea value={editingNote.text} onChange={e=>setEditingNote({...editingNote,text:e.target.value})} className="w-full px-3 py-1.5 rounded text-xs bg-gray-950 border border-gray-850 text-white resize-none" rows={2}/><div className="flex gap-1 mt-2"><button onClick={async()=>{await apiFetch(`/api/teacher/notes/${n.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:editingNote.text})});setEditingNote(null);loadAll()}} className="px-2 py-1 bg-emerald-500 text-white rounded text-[10px]">Save</button><button onClick={()=>setEditingNote(null)} className="px-2 py-1 bg-gray-800 text-gray-300 rounded text-[10px]">Cancel</button></div></>:<p className="text-xs text-gray-300">{n.text}</p>}<div className="flex gap-1 mt-2"><button onClick={()=>setEditingNote(n)} className="text-[10px] text-blue-400 hover:underline">Edit</button><button onClick={async()=>{if(!confirm('Delete?'))return;await apiFetch(`/api/teacher/notes/${n.id}`,{method:'DELETE'});loadAll()}} className="text-[10px] text-red-400 hover:underline">Delete</button></div></div>)})}</div>}
        </div>}

        {selectedStudent&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm" onClick={()=>setSelectedStudent(null)}><div className={`w-full max-w-lg rounded-2xl border p-6 max-h-[80vh] overflow-y-auto ${theme==='dark'?'bg-[#101424] border-gray-800 text-white':'bg-white border-gray-200 text-gray-900'}`} onClick={e=>e.stopPropagation()}><div className="flex justify-between mb-4"><h3 className="font-bold">{selectedStudent.student?.name}</h3><button onClick={()=>setSelectedStudent(null)} className="text-gray-500 hover:text-white">✕</button></div><div className="space-y-4 text-xs"><div><span className="text-gray-500">Email:</span> {selectedStudent.student?.email} · <span className="text-gray-500">Status:</span> {selectedStudent.student?.status} · <span className="text-gray-500">Target:</span> {selectedStudent.student?.targetScore||'—'} · <span className="text-gray-500">Avg:</span> {selectedStudent.student?.currentAvg||'—'}</div><div><span className="text-gray-500">Subs:</span> {selectedStudent.submissions?.length||0} · <span className="text-gray-500">Mocks:</span> {selectedStudent.tests?.length||0} · <span className="text-gray-500">Lessons:</span> {selectedStudent.completedLessons}</div>{selectedStudent.submissions?.length>0&&<div><h4 className="font-bold text-gray-400 mb-1">Recent Submissions</h4><div className="space-y-1">{selectedStudent.submissions.slice(0,5).map((s:any)=><div key={s.id} className="flex justify-between"><span className="font-mono">{s.taskCode}</span><span className={s.status==='graded'?'text-emerald-400':'text-amber-400'}>{s.score??'—'}</span></div>)}</div></div>}</div></div></div>}
      </div>
    </div>
  );
};
