import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  const name = process.env.ADMIN_NAME || 'Admin';

  if (!email) {
    throw new Error('ADMIN_EMAIL is required');
  }

  if (!password || password.length < 16) {
    throw new Error('ADMIN_PASSWORD is required and must be at least 16 characters');
  }

  const hashedPassword = await bcrypt.hash(password, 10);

  const user = await prisma.user.upsert({
    where: { email },
    update: {
      password: hashedPassword,
      role: 'admin',
      status: 'Active',
    },
    create: {
      email,
      password: hashedPassword,
      name,
      role: 'admin',
      status: 'Active',
      targetScore: 79,
      currentAvg: 0,
    },
  });

  console.log('Admin account ready:');
  console.log(`Email: ${user.email}`);
  console.log('Password: generated by caller, not printed by script');
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
